In [3]:
%load_ext autoreload
%autoreload 2
# load general packages
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('seaborn-whitegrid')
import MODEL
from MODEL import TheModel
import time
import tools

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [5]:
model = TheModel()
t0 = time.time()  # set the starting time
model.setup()
#tools.GaussHermite_lognorm(par.sigma_epsilon,par.Nxi)
model.create_grids()
model.solve()
par   = model.par
sol   = model.sol
t1 = time.time() # set the ending time
print(f'time: {t1-t0:.8} seconds') # print the total time
#print(f'{sol.m_logsum:.2}')
#print(sol.m_logsum[par.T-1,0,0])

#sol.m[par.T-1,i_a,i_k,i_h] = m
 #                   sol.c[par.T-1,i_a,i_k,i_h] = m
 #                   sol.v[par.T-1,i_a,i_k,i_h]

#print(par.xi)
#print(sol.m[par.T-1,8,2,2])
#print(sol.m[par.T-1,0,0,2])
#print(sol.v[par.T-1,2,2,2])

time: 76.900985 seconds


In [ ]:
fig = plt.figure(figsize=(8,5))
ax= plt.add_subplot(1,1,1)
ax.scatter(par.grid_m,sol.c[par.T-1,i_a,i_k,i_h])


def figure_multi_dim(par,sol,h):
    if h == 0:
        print(f'h=0')
        ts = [par.T, par.T-1, par.T-2, par.T-3, par.T-4]
    elif h ==1:
        print(f'h=1/2')
        ts = [par.T, par.T-1, par.T-2, par.T-3, par.T-4]
    else:
        print(f'h=1')
        ts = [par.T, par.T-1, par.T-2, par.T-3, par.T-4]
    fig = plt.figure(figsize=(8,5))
    ax = fig.add_subplot(1,1,1)
    for i in ts:
        ax.scatter(par.grid_m,sol.c[i-1,h,:,i_p], label=f't = {i}')
    ax.set_xlabel(f"$m_t$")
    ax.set_ylabel(f"$c(m_t,z_{{t+1}} = {z}, p = {p:.3})$")
    ax.set_xlim([0, 5])
    ax.set_ylim([0,3])
    ax.set_title(f'Consumption function')
    plt.legend()
    plt.show()

figure_multi_dim(model.par,model.sol,1)
figure_multi_dim(model.par,model.sol,2)
figure_multi_dim(model.par,model.sol,3)

In [366]:
##print(f'{par.grid_m}')
for h in range(3):
    print(f'h range: {h} (if 0:0, 1:1/2 and 2:1)')
    print(f'c: {sol.c[par.T-1,h,:]}')
    print(f'v: {sol.v[par.T-1,h,:]}')

h range: 0 (if 0:0, 1:1/2 and 2:1)
c: [[[ 1.00001001  1.00001001  1.00001001  1.00001001]
  [ 1.00001395  1.00001463  1.00001537  1.00001629]
  [ 1.00001789  1.00001925  1.00002073  1.00002258]]

 [[ 1.02442439  1.02442439  1.02442439  1.02442439]
  [ 1.03404582  1.03570672  1.03751154  1.03977071]
  [ 1.04366725  1.04698905  1.05059869  1.05511703]]

 [[ 1.0489202   1.0489202   1.0489202   1.0489202 ]
  [ 1.0681912   1.07151787  1.07513278  1.07965773]
  [ 1.08746221  1.09411553  1.10134536  1.11039526]]

 ...

 [[ 6.7586032   6.7586032   6.7586032   6.7586032 ]
  [ 9.0270749   9.4186704   9.84419708 10.37684851]
  [11.29554659 12.0787376  12.92979095 13.99509381]]

 [[ 6.8712188   6.8712188   6.8712188   6.8712188 ]
  [ 9.18405286  9.58330643 10.01715473 10.56022272]
  [11.49688692 12.29539406 13.16309066 14.24922665]]

 [[ 7.00000001  7.00000001  7.00000001  7.00000001]
  [ 9.36356452  9.77157545 10.21493992 10.76991974]
  [11.72712904 12.54315089 13.42987983 14.53983948]]]
v: [[[ 1